### ISSUE TITLE
Add date filtering

### ISSUE THREAD

**Issue by mahmoud** [hatnote/hashtags#4]
Many campaigns, like #1lib1ref, run on a regular basis. It would be [useful to users](https://twitter.com/jessamyn/status/953119784148889600) to offer date filtering to get better summary stats at the top of a search results page.

**Comment by Samwalton9** [comment]
See https://github.com/hatnote/hashtag-search/issues/18 - this is up and running at https://tools.wmflabs.org/hashtags-test.

I'll work on the final couple of tasks noted at that Issue and then submit a pull request soon :)

**Comment by jessamynwest** [comment]
When I did a check on 1lib1ref hashtag the results I got didn't seem to match the data. You can see this image. 

![screen shot 2018-01-21 at 19 06 53](https://user-images.githubusercontent.com/698448/35200544-87209984-fede-11e7-9a42-bbaeb5ff4410.jpg)

I told it to search 13jan - 21jan but the tool says that "#1lib1ref First appeared 18 Jan 2018" and so only gives me results from this date.Not sure why. Thoughts?

**Comment by Samwalton9** [comment]
Should have explained that - the test tool doesn't use the main database right now (I want it to: https://phabricator.wikimedia.org/T185242) and I only collected data on the 18th and 19th of Jan. Appreciate that's not hugely helpful for testing, I'm going to get it set up recording data on a regular basis like the actual tool does.

**Comment by slaporte** [comment]
Sam addressed this in hatnote/hashtag-search#23.  Thanks so much, Sam!
