### ISSUE TITLE
Add 'br' lang

### ISSUE THREAD

**Issue by belett** [hatnote/hashtags#5]
Hi,

Could you add 'br' lang to this tool?
(for the context: Pymouss - not a librarian but a #1lib1ref enthusiast - add 4 refs last night : https://br.wikipedia.org/wiki/Dibar:Degasadenno%C3%B9/Pymouss )

**Comment by slaporte** [comment]
Added [br wikipedia](https://tools.wmflabs.org/hashtags/search/1lib1ref?lang=br)!
